[package]
name = "meili_updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }
axum = "0.7.2"
sentry = { version = "0.32.0", features = ["debug-images"] }
lazy_static = "1.4.0"
log = "0.4.20"
env_logger = "0.10.1"
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.11.0"
meilisearch-sdk = "0.24.3"
futures = "0.3.29"
serde = { version = "1.0.193", features = ["derive"] }
